
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
    health:
      show-details: always
    prometheus:
      enabled: true
      cache:
        time-to-live: 0ms


server:
  port: 8080
  servlet:
    contextPath: "/"

service:
  context: "/api/v1/"

app:
  name: openapiexample

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

spring:
  web-application-type: none
  flyway:
    # baseline-on-migrate: true
    # check-location: false
    # locations: classpath:db/migration
    # schemas: hello-world
    enabled: false